name: generate-youtube-music-widget
description: Generate a YouTube music widget
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install system deps
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y ffmpeg yt-dlp

    - name: Install python deps
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install feedparser requests

    - name: generate youtube music widget
      shell: bash
      run: |
        python tools/generate_widget.py
