import random
import re
from html import unescape
from dataclasses import dataclass

import feedparser
import requests


@dataclass(frozen=True)
class YouTubeVideo:
    video_id: str
    channel_name: str
    title: str
    url: str
    thumbnail_url: str
    duration_seconds: int
    duration_label: str


class YouTubeClient:
    def __init__(self, *, timeout: int = 25) -> None:
        self.timeout = timeout

    def fetch_playlist_entries(self, playlist_id: str) -> list:
        playlist_url = (
            f"https://www.youtube.com/feeds/videos.xml?playlist_id={playlist_id}"
        )
        r = requests.get(
            playlist_url,
            headers={
                "User-Agent": "Mozilla/5.0",
                "Accept": "application/atom+xml,application/xml;q=0.9,*/*;q=0.8",
            },
            timeout=self.timeout,
        )
        r.raise_for_status()

        playlist_entries = feedparser.parse(r.content).entries
        if not playlist_entries:
            raise RuntimeError(f"Failed to read the playlist RSS: {playlist_url}")

        return playlist_entries

    def pick_random_entry(self, playlist_id: str) -> YouTubeVideo:
        entries = self.fetch_playlist_entries(playlist_id)
        entry = random.choice(entries)

        video_id = entry.get("yt:videoId") or entry.get("id").split(":")[-1]
        title = entry.get("title")
        if not video_id or not title:
            raise RuntimeError("An invalid video entry was selected.")
        url = f"https://www.youtube.com/watch?v={video_id}"

        thumb_url = f"https://i.ytimg.com/vi/{video_id}/mqdefault.jpg"
        channel_name = "Unknown"
        if "author" in entry:
            channel_name = entry.author
        elif "authors" in entry and entry.authors:
            channel_name = entry.authors[0].get("name", "Unknown")

        channel_name = self._format_channel_name_with_album(
            channel_name=channel_name,
            title=title,
            entry=entry,
        )
        duration_seconds = self._extract_duration_seconds(entry=entry, video_id=video_id)

        return YouTubeVideo(
            video_id=video_id,
            title=title,
            url=url,
            thumbnail_url=thumb_url,
            channel_name=channel_name.strip(),
            duration_seconds=duration_seconds,
            duration_label=self._format_duration(duration_seconds),
        )

    @staticmethod
    def _format_channel_name_with_album(channel_name: str, title: str, entry: dict) -> str:
        cleaned = channel_name.strip()
        if not cleaned.endswith(" - Topic"):
            return cleaned

        artist = cleaned[: -len(" - Topic")].strip()
        album = YouTubeClient._extract_album_name(entry=entry, title=title)
        if album:
            return f"{artist} • {album}"
        return artist

    @staticmethod
    def _extract_album_name(entry: dict, title: str) -> str | None:
        raw = (
            entry.get("media_description")
            or entry.get("summary")
            or entry.get("description")
            or ""
        )
        if not raw:
            return None

        lines = [unescape(line).strip() for line in raw.splitlines() if line.strip()]
        if not lines:
            return None

        lowered = [line.lower() for line in lines]
        if not any("provided to youtube by" in line for line in lowered):
            return None

        for i, line in enumerate(lines):
            if "·" not in line:
                continue

            if title.casefold() not in line.casefold():
                continue

            for candidate in lines[i + 1 :]:
                c = candidate.strip()
                lc = c.lower()
                if not c:
                    continue
                if c.startswith("℗"):
                    break
                if lc.startswith("released on:") or "auto-generated by youtube" in lc:
                    break
                if "·" in c:
                    continue
                return c

        return None

    def _extract_duration_seconds(self, entry: dict, video_id: str) -> int:
        media_content = entry.get("media_content") or []
        if isinstance(media_content, list):
            for item in media_content:
                if not isinstance(item, dict):
                    continue
                raw = item.get("duration")
                if raw is not None:
                    try:
                        seconds = int(raw)
                        if seconds > 0:
                            return seconds
                    except (TypeError, ValueError):
                        pass

        yt_duration = entry.get("yt_duration")
        if isinstance(yt_duration, dict):
            raw_seconds = yt_duration.get("seconds")
            if raw_seconds is not None:
                try:
                    seconds = int(raw_seconds)
                    if seconds > 0:
                        return seconds
                except (TypeError, ValueError):
                    pass

        try:
            return self._fetch_duration_seconds_from_watch_page(video_id)
        except RuntimeError as e:
            print(f"[WARN] Failed to fetch exact video duration ({e}) → using 04:00")
            return 240

    def _fetch_duration_seconds_from_watch_page(self, video_id: str) -> int:
        watch_url = f"https://www.youtube.com/watch?v={video_id}"
        r = requests.get(
            watch_url,
            headers={
                "User-Agent": "Mozilla/5.0",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            },
            timeout=self.timeout,
        )
        r.raise_for_status()
        html = r.text

        m = re.search(r'"lengthSeconds":"(\d+)"', html)
        if m:
            return int(m.group(1))

        m = re.search(r'"approxDurationMs":"(\d+)"', html)
        if m:
            return max(1, int(m.group(1)) // 1000)

        raise RuntimeError("lengthSeconds not found in watch page")

    @staticmethod
    def _format_duration(seconds: int) -> str:
        if seconds < 0:
            seconds = 0
        h, rem = divmod(seconds, 3600)
        m, s = divmod(rem, 60)
        if h > 0:
            return f"{h}:{m:02d}:{s:02d}"
        return f"{m:02d}:{s:02d}"

    def image_url_to_base64(self, url: str) -> tuple[bytes, str]:
        data = requests.get(
            url,
            headers={"User-Agent": "Mozilla/5.0", "Accept": "image/*,*/*;q=0.8"},
            timeout=self.timeout,
        )
        data.raise_for_status()

        ctype = data.headers.get("Content-Type", "").split(";")[0].strip().lower()
        if not ctype:
            ctype = "image/jpeg"

        return data.content, ctype
